# Generated by Django 4.1.6 on 2023-02-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_by',
            new_name='owner',
        ),
    ]
